spring.datasource.url=jdbc:postgresql://ep-hidden-dream-ay3ude7x-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_HoD76TxwjFJk

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true